## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Colors configuration -------------------------------------

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#8FA1B3"
magenta = "#B48EAD"
cyan    = "#96B5B4"
white   = "#E5E9F0"

[colors.bright]
black   = "#4C566A"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#8FA1B3"
magenta = "#B48EAD"
cyan    = "#96B5B4"
white   = "#ECEFF4"
